FROM elixir:1.11

RUN mkdir /opt/elixir-ls && \
    cd /opt/elixir-ls && \
    wget https://github.com/elixir-lsp/elixir-ls/releases/download/v0.7.0/elixir-ls-1.11.zip && \
    unzip elixir-ls-1.11.zip && \
    rm elixir-ls-1.11.zip && \
    chmod a+x *.sh

RUN mix local.rebar --force && mix local.hex --force

ENV PATH="/opt/elixir-ls:${PATH}"
