FROM elixir:1.10

RUN mkdir /opt/elixir-ls && \
    cd /opt/elixir-ls && \
    wget https://github.com/elixir-lsp/elixir-ls/releases/download/v0.7.0/elixir-ls-1.8.2.zip && \
    unzip elixir-ls-1.8.2.zip && \
    rm elixir-ls-1.8.2.zip && \
    chmod a+x *.sh

ENTRYPOINT ["/opt/elixir-ls/language_server.sh"]
