name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run shellcheck
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
